[package]
name = "sauna-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
email_address = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
